## Crear un dataframe del csv dado

In [97]:
import pandas as pd
# DataFrame
df_csv = pd.read_csv('argentina_cars.csv')
display(df_csv)
# Paso a excel para ver mas facil los datos
df_csv.to_excel('argentina_cars.xlsx', sheet_name='Autitos', index=False)

,money,brand,model,year,color,fuel_type,door,gear,motor,body_type,kilometres,currency
0,10350000,Toyota,Corolla Cross,2022,Plateado,Nafta,5.0,Automática,NaN,SUV,500,pesos
1,10850000,Jeep,Compass,2022,Blanco,Nafta,5.0,Automática,2.4,SUV,500,pesos
2,35500,Jeep,Compass,2022,Gris oscuro,Nafta,5.0,Automática,2.4,SUV,500,dólares
3,19000,Citroën,C4 Cactus,2022,Gris oscuro,Nafta,5.0,Automática,NaN,SUV,550,dólares
4,5800000,Toyota,Corolla,2019,Gris,Nafta,4.0,Manual,1.8,Sedán,9000,pesos
...,...,...,...,...,...,...,...,...,...,...,...,...
505,5250000,Chevrolet,Tracker,2018,Gris,Nafta,5.0,Automática,1.8,SUV,52000,pesos
506,46000,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,49000,dólares
507,3960000,Peugeot,2008,2017,Blanco,Nafta,5.0,Manual,1.6,SUV,75358,pesos
508,44900,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,57500,dólares
509,2890000,Toyota,Etios,2015,Gris,Nafta,5.0,Manual,1.5,Hatchback,84000,pesos

## Eliminar los registros que tengan nulos

In [98]:
df_csv_clean = df_csv.dropna()
display(df_csv_clean)

,money,brand,model,year,color,fuel_type,door,gear,motor,body_type,kilometres,currency
1,10850000,Jeep,Compass,2022,Blanco,Nafta,5.0,Automática,2.4,SUV,500,pesos
2,35500,Jeep,Compass,2022,Gris oscuro,Nafta,5.0,Automática,2.4,SUV,500,dólares
4,5800000,Toyota,Corolla,2019,Gris,Nafta,4.0,Manual,1.8,Sedán,9000,pesos
5,34500,Jeep,Compass,2022,Negro,Nafta,5.0,Automática,1.3,SUV,10500,dólares
6,25000,Kia,Sorento,2014,Negro,Diésel,5.0,Automática,2.2,SUV,156000,dólares
...,...,...,...,...,...,...,...,...,...,...,...,...
505,5250000,Chevrolet,Tracker,2018,Gris,Nafta,5.0,Automática,1.8,SUV,52000,pesos
506,46000,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,49000,dólares
507,3960000,Peugeot,2008,2017,Blanco,Nafta,5.0,Manual,1.6,SUV,75358,pesos
508,44900,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,57500,dólares
509,2890000,Toyota,Etios,2015,Gris,Nafta,5.0,Manual,1.5,Hatchback,84000,pesos

## Pasar la columna `money` a dolares cuando `currency` sea igual a pesos. Valor del dolar = 1500. Luego eliminar la columna `currency`

In [123]:
display(df_csv_clean.loc[df_csv_clean['currency'] == 'pesos', 'money'] // 1500)
# LO HACE, pero no lo puedo guardar porque me sobreescribe todo a la mierda

# Parche para seguir con ejercicios
df_dolares = df_csv_clean

df_dolares = df_dolares.drop(columns='currency')

display(df_dolares)

1      7233
4      3866
9      4533
13     3993
15     1400
       ...
503    5133
504    1926
505    3500
507    2640
509    1926
Name: money, Length: 411, dtype: int64

,money,brand,model,year,color,fuel_type,door,gear,motor,body_type,kilometres
1,10850000,Jeep,Compass,2022,Blanco,Nafta,5.0,Automática,2.4,SUV,500
2,35500,Jeep,Compass,2022,Gris oscuro,Nafta,5.0,Automática,2.4,SUV,500
4,5800000,Toyota,Corolla,2019,Gris,Nafta,4.0,Manual,1.8,Sedán,9000
5,34500,Jeep,Compass,2022,Negro,Nafta,5.0,Automática,1.3,SUV,10500
6,25000,Kia,Sorento,2014,Negro,Diésel,5.0,Automática,2.2,SUV,156000
...,...,...,...,...,...,...,...,...,...,...,...
505,5250000,Chevrolet,Tracker,2018,Gris,Nafta,5.0,Automática,1.8,SUV,52000
506,46000,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,49000
507,3960000,Peugeot,2008,2017,Blanco,Nafta,5.0,Manual,1.6,SUV,75358
508,44900,Volkswagen,Amarok,2019,Gris,Diésel,4.0,Automática,3.0,Pick-Up,57500
509,2890000,Toyota,Etios,2015,Gris,Nafta,5.0,Manual,1.5,Hatchback,84000

## Pasar la columna `money` del dataframe a un array de numpy con el metodo `df['money'].to_numpy()`

In [ ]:
import numpy as np

array_dolares = df_dolares['money'].to_numpy()


print(array_dolares)

[10850000    35500  5800000    34500    25000    12300    35500  6800000
    38500    20500  5990000  2100000  2940000  2050000  4120000  4100000
    15000  5099000  8300000  4500000  2400000  5200000  7500000  2450000
  5200000  2450000  2585000  4300000  7589900  1950000  3050000  3150000
  9389900  3290000    14900  3150000  3100000  2750000  3750000 11290000
    46900  2520000    43000    17900  5850000    32000   185000  2500000
  1700000  2690000  4400000  3990000  3950000  2290000  3900000  3750000
  2650000    58000  5200000  3800000  3650000  4599999  2280000  6489000
  4450000  8490000  3600000  6750000  2789900  3189900  3189900  2950000
  4250000  3450000  4200500  4590000  4237000  2550000 11900000  2100500
  5650000  3500000  5289900  2350000  3800000  5889900    78500  7550000
  3590000  6190000  1610000  1960000  2280000  2100000  1650000  3590000
  2150000  3800000  1550000  1595000  4700000  2800000    42900  7500000
  6300000  3450000  9500500  3890000  4200000  6500000  4289900 12400000
  4189900  3650000  6300000  6299000    16000  2700000  1975000  3650000
  1890000  6500000  5200000  4689900   115700  3000000  2700500  2000500
  2000500  2000500  4429800  2450500  5849000  1650000  2450500  5029000
  5200000  1850000  2849900  3489900  3350000  8489900  3889900  3650000
  2589900  3899900  3689900  5100000  5489900  4190000  8989900  6489900
  7289900  2789900  2489900  6700000  3890000  5780000  4400000    52900
  2158000  2200000  2189900  3689900    17500  3689900  4690000  8990000
  4890000  3200000  2500000  2950000  6290000  3900000  7880000 10900000
  1750000  4250000  3520000  9450000  3650000  4779900  3490000  3200000
  3490000  2689900  3489900  5389900  3348000  3402000  3990000    16500
  4589900  3539000  3726000  3700000  5900000  1750000  3769200  2930000
  1900000    95000  3100000  3780000  2850000  2500000  1900000    47700
    64900  7970000  6590000  4089900  4989900  2649900  8459900  2350000
  7890000  5990000    12500  7489000  4400000  2510000  9300000  3499900
  2900000  5900000  3459900  3600000  3799000  4250000  2880000  2200000
  6490000  7190000  4589900  3489900  8600000    10599  7950000    28500
  3990000  3490000  3564000  3449900  3789900    34990  7899900  3150000
  2950000  4459900  3150000    13499  3485000  3189900  3289900 12490000
  2689900    35499  3489900  3589900  2989900 13949900  3189900  2500000
 12489000  5889000  3700000  3089900  6489900  4389900  2800000  4630000
    26990     8000  3989900  7150000  3450500  3500000  8500000  2750000
 10500000  3250000  2649900 11900000  6690000 10900000  5099999  3290000
  5390000  2550000  2990000  3300000  4690000  5099999  3299999 11850000
  4900000  7300000  3900000  8500000    14500    43990  4000000  3000000
    77500  7390000    89990  8500000    33999  5480000  4400000  8250000
  5800000  2700000  9250000  2440000  2189900  2977000    26990  3150000
  3000000  3000000  6000000  3300000  2600000  3280000  4690000  1895000
  4350000 11200000 11890000  4200000  5890000  4200000  8990000  3000000
    77500  4690000 11195000  5990000  5450500    16300  6190000  7890000
  9590000    36990 10400000  1950000 14299000    26500  4990000  5990000
  2689000  2700000    13900  7040000  3400000  2900000  2500000  2090000
  4700000    65900    77490    16500  2850000  5050000  3800000  6700000
  4989900  6290000  7789900    31000  5890000  7889900  3489900    79000
    46999  4490000  6200000   128000    90000    68000   235000  3280000
    30000  6199999    15000  4739600  4150000  2550000  2800000  3150000
    24800  2050000    34900 10900000  2050000  8300000  3189900  8300000
  1200000 11400000  3600000  4700000  2800000  4600000  3800000    19500
  6646000  3355000  2800000  7100000  2165000  4890000    41990 11989900
     8900 10359900 10900000    10000 10359900    23000  7390000    13500
  9300000  3790000  5890000    15990    24500  4989900  9900000  7250000
  4100000  4100000  9900000  6589900    14500  2400000    30990   430000
    13499  3600000  3350000  2650000  5350000  5650000  3600000  6790000
  1860000  4800000  4190000  3400000    39990  2790000  8900000  1990000
  9100000  3075000  3290000  2390000    46990  2850000  3190000    90000
  4950000  2300000    15900  3098900  2499700  4149800  3998700  3249800
  2799800  3949800  2781000  4449800 11290000  3450000  3000000  3190000
  7700000  2890000  5250000    46000  3960000    44900  2890000]

## Hacer un grafico de la campana de Gauss con la media y la variación con la funcion random normal

## Renombrar columnas a español

## Agrupar los registros de la misma Marca y aplicar el promedio de precios de sus autos

## Pasar columna `year` a formato datetime

## Quedarse solo con la columna `Marca` y `promedio_precios`

## Graficar promedio precio por marca

## Generar un nuevo excel con el dataframe creado